runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /resources/bootstrap
 static_dir: resources/bootstrap

- url: /static
 static_dir: static/css

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
